# Dimer in Solution Config File
simulation_name : "dimer-lj-sim"
integrator : "metropolis"
integrator_args : {
  temp : 1,
}
x_0 : [2 , 0]
out_freq : 100
n_steps : 50000
system_params : {
  N : 36,
  rho : 0.7,
  placement_method : "lattice",
  boundary_conditions : "none",
  potential : "LJ-rep",
  sigma : 1.1,
  epsilon : 1.0,
}
bond_indexes : [14, 15]
