# Double Well Config File
simulation_name : "double-well-sim"
integrator : "metropolis"
integrator_args : {
  temp : 1,
  sigma : 0.02,
  adjust_sigma : False,
}
x_0 : [-2, 0]
out_freq : 100
n_steps : 100000
