# Double Well Config File
simulation_name : "muller-sim"
integrator : "metropolis"
integrator_args : {
  temp : 1,
  sigma : 0.02,
  adjust_sigma : False,
}
x_0 : [-0.5, 1.5]
out_freq : 100
n_steps : 100000