# Double Well Config File
simulation_type : "double-well"
integrator : "metropolis"
integrator_args : {
  temp : 1,
  sigma : 0.02,
  adjust_sigma : False,
}
x_0 : [0.5, 0]
out_freq : 100
n_steps : 100000